/* eslint-disable @next/next/no-img-element */
import { event } from './style.css';
import Head from 'next/head';
// css

export default function Event({}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={event}>
        <div>사건 사고 개별 페이지</div>
      </main>
    </>
  );
}
