import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useUserStore } from '@/store/user';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { accessToken, username, saveUser, removeUser } = useUserStore();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{username}</div>
        <div>{accessToken}</div>
        <div>{username ? '회원' : '비회원'}</div>
      </main>
    </>
  );
}
